# Generated by Django 5.2.12 on 2026-03-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(unique=True)),
                ('recommended_book_ids', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
