# Generated by Django 5.2.13 on 2026-04-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('product_id', models.IntegerField(db_index=True)),
                ('action', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('add_to_cart', 'Add to Cart'), ('purchase', 'Purchase'), ('remove_cart', 'Remove Cart'), ('search', 'Search'), ('review', 'Review')], db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
                ('synced_to_neo4j', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['user_id', 'timestamp'],
                'indexes': [models.Index(fields=['user_id', 'timestamp'], name='api_behavio_user_id_ede5a8_idx'), models.Index(fields=['synced_to_neo4j'], name='api_behavio_synced__3a36dd_idx')],
            },
        ),
    ]
