# Generated by Django 5.2.12 on 2026-03-17 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_book_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category_id',
        ),
    ]
